### ISSUE TITLE
My Weather indicator stopped working in Ubuntu 22.04

### ISSUE THREAD

**Issue by freewee** [atareao/my-weather-indicator#136]
Hi
I get My-weather-indicator working on Ubuntu 24.04 after some problems, but it stopped working on a laptop with Ubuntu 22.04 after an update, with this error:

/opt/extras.ubuntu.com/my-weather-indicator/bin/my-weather-indicator
Traceback (most recent call last):
  File "/opt/extras.ubuntu.com/my-weather-indicator/bin/my-weather-indicator", line 35, in <module>
    from myweatherindicator import main
  File "/opt/extras.ubuntu.com/my-weather-indicator/share/my-weather-indicator/myweatherindicator.py", line 29, in <module>
    from datetime import datetime, UTC
ImportError: cannot import name 'UTC' from 'datetime' (/usr/lib/python3.10/datetime.py)
What can I do ? Thank you!

**Comment by adefaria** [comment]
Me too! I've been working on this trying to resolve it but apparently this is a known issue.

I also have a problem of whenever I reboot and my-weather-indicator comes up it colors the background oddly and if I restart it it comes out OK.

**Comment by freewee** [comment]
Solved with the last update for me Thank you!
